[package]
name = "swab"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive"] }
globset = "0.4.18"
walkdir = "2.5.0"

[dev-dependencies]
tempfile = "3.24.0"
